### ISSUE TITLE
EO Povery Review

### ISSUE THREAD

**Issue by cjerzak** [AIandGlobalDevelopmentLab/eo-poverty-review#1]
@ksakamoto09 Here is a GitHub where we can put supplementary information for the review.

**Comment by cjerzak** [comment]
Tentatively changed the title to "An Overview of Earth Observation in Poverty Research" -- We can iterate. I am worried about having a title with too much complexity that makes our contribution less decisive.

**Comment by ksakamoto09** [comment]
@cjerzak Thanks! I uploaded the .bib files and put them in the overleaf doc as well.

**Comment by cjerzak** [comment]
Awesome!
