### ISSUE TITLE
Feedback April

### ISSUE THREAD

**Issue by adeldaoud** [AIandGlobalDevelopmentLab/eo-poverty-review#2]
The following are some highlevel comments, @ksakamoto09 

- [x] 1.	We can make the opening paragraphs stronger. It is a little generic right now. We should create a gap and relevance statement in the first paragraph by clarifying more exactly where geography of poverty may benefit from EO-ML powered causal inference. IT should be making clear why a review is relevant. For that, we can emphasize that the two streams of literature (geo of poverty) and EO-ML has up to recently evolved independently. Thus, the literature needs more information where there are synergies. This review contributes towards that. 
- [ ] 2.	In terms of section 2.5, see Lundberg et al (See attached) for summarizing methods in tables, especially if we want to include estimators. It should be made clear why the reader should think about these estimators.
- [ ] 3.	We should also discuss common estimands . 
- [ ] 4.	As previously discussed, I am not sure we want to conduct a quantitative literature survey (section 5). Although some of the summaries are quantitative, we want to conduct a qualitative analysis of key findings in the literature. This goes back to defining a schema. While we cannot really summarize all papers, we want to highlight trends and insights based on our 46 paper and 24 preprints. That should be the core foundational results of the paper, which underpings our main contribution – future direction, gaps, and open research questions. 
- [x] 5.	Generally, the paper has too many subsection with short paragraphs. Either we want to build out those section with deeper discdussions or reduce the nr of sections.
- [x] 6. See minor comments in the manuscript. 

[Lundberg et al_2021_What Is Your Estimand.pdf](https://github.com/AIandGlobalDevelopmentLab/eo-poverty-review/files/15256220/Lundberg.et.al_2021_What.Is.Your.Estimand.pdf)

**Comment by ksakamoto09** [comment]
@adeldaoud thanks for the feedback, and the lundberg et al paper. I think the issue is that many of the papers don't really have a estimand or it's not super clear since they are focused on the estimation strategies and improving them. I guess we can separate out methods only papers and ones measuring causal effects?

**Comment by ksakamoto09** [comment]
actually I think I have a way, I will just separate out by 

- does it have an estimand, then what it is. 
- does it focus on an identification strategy, then what it is (some of them are only intersted in causal discovery)
- does it focus on an estimation strategy, then what it is (some of the are on interested in the estimation model)

**Comment by adeldaoud** [comment]
> I think the issue is that many of the papers don't really have a estimand or it's not super clear since they are focused on the estimation strategies and improving them. I guess we can separate out methods only papers and ones measuring causal effects?

@ksakamoto09, that is fine that they do not have that, as we will just report that they are unclear about their estimands. 

>does it have an estimand, then what it is.
>does it focus on an identification strategy, then what it is (some of them are only intersted in causal discovery)
>does it focus on an estimation strategy, then what it is (some of the are on interested in the estimation model)

These are good pieces for the annotation schema. What schema are we using current? Based on my previous feedback, I can take a look where we stand now and what else we need.

**Comment by adeldaoud** [comment]
@ksakamoto09 what is the update on this feedback? If you have incorporated it tick off the boxes and explain where and how it has been addressed.

**Comment by cjerzak** [comment]
Let's move this conversation to another forum as the GitHub comments here will now be used for people to suggest additional papers for inclusion in this evolving list. 

https://github.com/AIandGlobalDevelopmentLab/eo-poverty-review/

**Comment by cjerzak** [comment]
Let's move this conversation to another forum as the GitHub comments here will now be used for people to suggest additional papers for inclusion in this evolving list. 

https://github.com/AIandGlobalDevelopmentLab/eo-poverty-review/
